name: CD - Deploy con Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy por SSH (git pull en el servidor)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}           # Tu IP del servidor
          username: ${{ secrets.SERVER_USER }}     # Tu usuario (alumno)
          key: ${{ secrets.SSH_PRIVATE_KEY }}     # Tu llave privada completa
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # La passphrase de tu llave
          script: |
            set -e
            cd ~/lemp-sites/anabella_villaverde/Practico_Evaluativo_Gestor_de_Libros
            git pull origin main
            echo "✅ Código actualizado en el servidor"


